config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms, only: [:new, :create, :show, :index]
  root 'rooms#index'
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :rooms, dependent: :destroy
has_many :messages, dependent: :destroy

def name
  email.split('@')[0]
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = 'Chatroom added!'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def show
    # includes used for eager loading
    @room = Room.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p>
  <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
  <%= message.body %>
</p>

app/views/rooms/_room.html.erb
<li><%= link_to "Enter #{room.title}", room_path(room) %></li>

app/views/rooms/index.html.erb
<h1>Chat rooms</h1>

<p><%= link_to 'New chatroom', new_room_path %></p>

<ul>
  <%= render @rooms %>
</ul>

app/views/rooms/new.html.erb
<h1>Add chatroom</h1>

<%= form_for @room do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit "Add!" %>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.title %></h1>

<div id="messages" data-room-id="<%= @room.id %>">
  <%= render @room.messages %>
</div>

<hr>

<%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'room_id', @room.id %>
  <div >
    <%= f.label :body %>
    <%= f.text_area :body %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post" %>
<% end %>